### ISSUE TITLE
how can i change adress or other checkbox option in motionbuilder use python

### ISSUE THREAD

**Issue by Bn-com** [Unity-Technologies/MeshSyncDCCPlugin#106]
is there any way?
Thanks~

**Comment by sindharta** [comment]
Unfortunately, the answer is probably no since Python can't execute C++ plugins as mentioned in the [MotionBuilder documentation](https://download.autodesk.com/us/motionbuilder/sdk-documentation/index.html?url=./files/WS73099cc142f4875539000486122982e6aa8-75ba.htm,topicNumber=d0e105).

That said, our team is not very familiar with MotionBuilder's Python API, so there might be another way.
For your reference, this is the link to [msmobuLayout](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/blob/dev/Plugins~/Src/MeshSyncClientMotionBuilder/msmobuLayout.cpp
) class where we are creating the layout for the MotionBuilder plugin.

**Comment by sindharta** [comment]
Closing due to non-activity.
Please feel free to reopen.
